= Docker + TYPO3 (Template)
:author:        Joschi Kuphal
:email:         joschi@tollwerk.de
:revdate:       May 1st, 2020
:revnumber:     1.0.0
:lang:          de
:orgname:       tollwerk GmbH
:description:   Template repository for Docker based TYPO3 projects
:keywords:      TYPO3, Docker, Fractal, Tenon

The files in this repository are meant to be used as the starting point for a new TYPO3 project based on the https://github.com/tollwerk/docker-tollwerk[Tollwerk Docker images]. Apart from a working Docker setup, only two files are necessary to kickstart a new project following this setup:

* link:docker-compose.yml[docker-compose.yml] to download and initialize the Docker images. The https://github.com/tollwerk/docker-tollwerk/blob/master/typo3/README.md[tollwerk/typo3] image is kinda "self-extracting" and will take care of the installation process.
* link:.env.example[.env.example] which will serve as template for a project specific environment file (`.env`)  you will have to craft before starting the Docker containers for the first time.

== Project kick-off

Before you can start working on your project on potentially many development machines, you have to create and configure an **original instance** which will also be used for your initial Git commit.

On the command line of your machine, change to the directory where your project should live and **create a shallow clone** of this repository (replace `<new_project_name>` accordingly):

. Navigate to your **project's parent directory**.
+
----
cd /path/to/project/parent
----
. Create a **shallow clone** of this repository (replace `<new_project_name>`).
+
----
git clone --depth=1 https://github.com/tollwerk/docker-template-typo3.git <new_project_name>
----
. Remove the tracking link to the original template repository.
+
----
git remote remove origin
----
. Reset ownership to yourself.
+
----
git commit --amend --reset-author -m "Initial Commit"
----

== Configuration & installation

. Rename the `.env.example` to `.env` and edit the environment variables inside to match your project requirements.
. Let Docker bring up the containers and install the rest of the project.
+
----
docker-compose up
----
+
[CAUTION]
Please be patient during the first start of the the Docker containers. There's a lot _composer_ has to install at this stage.

=== Dynamic production state updates

As soon as Docker has launched for the first time, a fresh TYPO3 instance should have been installed to your file system. In order to have updateable production states (data files and database contents), the `fileadmin` directory of your TYPO3 instance must be put under the control of a separate Git repository which is later included as a submodule of the main repository.

. Create a new online repository for your project's `fileadmin`.
. Copy the unique URL for your new repository to your clipboard.
. Change to the `fileadmin` directory:
+
[source,bash]
----
cd public/fileadmin
----
. In your local repository, from the command line, Create the following directory / file structure:
+
[source,bash]
----
├── .githooks
│   └── post-merge
└── .gitignore
----
+
The `post-merge` hook will watch out for a file named `database.sql` in the root directory of the repository which should contain a database dump corresponding to the file contents in the directory. Whenever the dump changes, an indicator file named `database.IMPORT_RESET` will be created. During startup, the TYPO3 docker container will look for the presence of this file (`public/fileadmin/database.IMPORT_RESET`) and — if present — replace the database with the contents of `database.sql` (and remove the indicator file afterwards).
+
..githooks/post-merge
[source,bash]
----
#!/usr/bin/env bash

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.githooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Drop update indicators for database
check_run database.sql "touch database.IMPORT_RESET"
----
+
TIP: You may copy the hook file of the same name from the main repository and just change the last two lines.
+
Temporary files (e.g. images) as well as the database update indicator shouldn't go to the repository:
+
..gitignore
[source,bash]
----
_temp_
_processed_
/database.IMPORT_RESET
----
. Make the Git hook executable, initialize the repository (replace the origin path with your clipboard content) and register the custom hook directory:
+
[source,bash]
----
# Change to the fileadmin directory
chmod +x .githooks/post-merge
git init
git remote add origin <new_project_fileadmin_repo_URL>
git config --local core.hooksPath .githooks/
----
. Commit and push to a branch (usually `master`).
+
[source,bash]
----
git add .
git commit -m "Initial commit"
git push -u origin master
----

== Push to a remote repository

. Create a new online repository for your project.
. Copy the unique URL for your new repository to your clipboard.
. In your local repository, from the command line, add the remote tracking information for the new repository and register the `fileadmin` repository as a submodule.
+
----
git remote add origin <new_project_repo_URL>
git submodule add <new_project_fileadmin_repo_URL> public/fileadmin
----
. Commit and push to a branch (usually `master`).
+
[source,bash]
----
git add .
git commit -m "Initial commit"
git push -u origin master
----
